"""
Integration tests for two-layer clip detection (find_all_boundaries + group_clips).

Fixture: tests/fixtures/test_15min_ocr_cache.json — raw OCR text from test_15min.mp4,
generated by scan() with interval=10, crop=250:110:385:370.

Golden reference for test_15min.mp4 (coarse, before refinement):
  Session boundaries at --gap 900:  [50, 140, 380, 480, 490, 560, 790]
  Daily boundaries:                  [50, 480]   (1/1→1/4 and 1/4→1/5 date changes)
  Scene boundaries:                  superset of session (all gap + large_gap)
"""
import json
from pathlib import Path

import pytest

from split_homevideo import _CACHE_FORMAT, filter_ocr_outliers, find_all_boundaries, group_clips, parse_timestamp

FIXTURE = Path(__file__).parent / "fixtures" / "test_15min_ocr_cache.json"
GAP_S = 900
TOLERANCE_S = 15

# Golden coarse boundary positions for session mode (large_gap only, pre-refinement).
GOLDEN_SESSION = [50.0, 140.0, 380.0, 480.0, 490.0, 560.0, 790.0]

# Golden coarse boundary positions for daily mode (date changes only).
# 50s: 1990-01-01 → 1990-01-04; 480s: 1990-01-04 → 1990-01-05
GOLDEN_DAILY = [50.0, 480.0]


@pytest.fixture(scope="module")
def samples():
    assert FIXTURE.exists(), (
        f"Fixture missing: {FIXTURE}. Run: python3 -c \""
        "from split_homevideo import scan; "
        "scan('test_15min.mp4', 10, '250:110:385:370', "
        "cache_path='tests/fixtures/test_15min_ocr_cache.json')\""
    )
    with open(FIXTURE) as f:
        cached = json.load(f)
    assert cached.get("cache_format") == _CACHE_FORMAT, (
        "Fixture uses old cache format — regenerate"
    )
    return [
        (float(t), parse_timestamp(text) if text else None)
        for t, text in cached["samples"]
    ]


@pytest.fixture(scope="module")
def boundaries(samples):
    return find_all_boundaries(filter_ocr_outliers(samples))


class TestSessionMode:
    def test_seven_boundaries(self, boundaries):
        cuts = group_clips(boundaries, mode="session")
        assert cuts[0] == 0.0
        n = len(cuts) - 1
        assert n == len(GOLDEN_SESSION), (
            f"Expected {len(GOLDEN_SESSION)} boundaries, got {n}: {cuts[1:]}"
        )

    def test_boundary_positions(self, boundaries):
        cuts = group_clips(boundaries, mode="session")
        for golden, actual in zip(GOLDEN_SESSION, sorted(cuts[1:]), strict=True):
            assert abs(actual - golden) <= TOLERANCE_S, (
                f"Boundary {actual:.0f}s is >{TOLERANCE_S}s from golden {golden:.0f}s"
            )

    def test_all_session_boundaries_are_large_gap(self, boundaries):
        cuts = group_clips(boundaries, mode="session")
        boundary_map = {b.video_t: b for b in boundaries}
        for vt in cuts[1:]:
            b = boundary_map.get(vt)
            assert b is not None and b.type == "large_gap", (
                f"Session cut at {vt}s is not large_gap"
            )


class TestDailyMode:
    def test_two_boundaries(self, boundaries):
        cuts = group_clips(boundaries, mode="daily")
        assert cuts[0] == 0.0
        n = len(cuts) - 1
        assert n == len(GOLDEN_DAILY), (
            f"Expected {len(GOLDEN_DAILY)} daily boundaries, got {n}: {cuts[1:]}"
        )

    def test_boundary_positions(self, boundaries):
        cuts = group_clips(boundaries, mode="daily")
        for golden, actual in zip(GOLDEN_DAILY, sorted(cuts[1:]), strict=True):
            assert abs(actual - golden) <= TOLERANCE_S, (
                f"Daily boundary {actual:.0f}s is >{TOLERANCE_S}s from golden {golden:.0f}s"
            )

    def test_daily_boundaries_cross_date(self, boundaries):
        cuts = group_clips(boundaries, mode="daily")
        boundary_map = {b.video_t: b for b in boundaries}
        for vt in cuts[1:]:
            b = boundary_map.get(vt)
            assert b is not None
            is_backward = b.cam_jump_s < -1800
            no_date = b.cam_before is None or b.cam_after is None
            date_change = (not no_date) and b.cam_before.date() != b.cam_after.date()
            assert no_date or is_backward or date_change, (
                f"Daily cut at {vt}s does not change date: {b.cam_before} → {b.cam_after}"
            )


class TestSceneMode:
    def test_more_boundaries_than_session(self, boundaries):
        session_cuts = group_clips(boundaries, mode="session")
        scene_cuts = group_clips(boundaries, mode="scene")
        assert len(scene_cuts) > len(session_cuts), (
            f"scene ({len(scene_cuts)}) should have more cuts than session ({len(session_cuts)})"
        )

    def test_includes_all_session_boundaries(self, boundaries):
        session_cuts = set(group_clips(boundaries, mode="session"))
        scene_cuts = set(group_clips(boundaries, mode="scene"))
        assert session_cuts.issubset(scene_cuts), (
            f"Scene missing session boundaries: {session_cuts - scene_cuts}"
        )

    def test_includes_gap_type_boundaries(self, boundaries):
        scene_cuts = set(group_clips(boundaries, mode="scene"))
        gap_boundaries = [b for b in boundaries if b.type == "gap"]
        assert len(gap_boundaries) > 0, "No gap-type boundaries found in fixture"
        for b in gap_boundaries:
            assert b.video_t in scene_cuts, (
                f"Gap boundary at {b.video_t}s missing from scene mode"
            )
